// neko-data.jsx — Phase 2 mock data
// 12 works (한영 혼합) covering 영화/시리즈/예능, OTT 5개 분포

const NEKO_OTTS = {
  netflix:  { id: 'netflix',  name: 'Netflix',   short: 'N',  color: '#E50914' },
  wavve:    { id: 'wavve',    name: 'Wavve',     short: 'W',  color: '#1351F9' },
  tving:    { id: 'tving',    name: 'TVING',     short: 'T',  color: '#FF153C' },
  watcha:   { id: 'watcha',   name: 'Watcha',    short: 'W',  color: '#FF0558' },
  disney:   { id: 'disney',   name: 'Disney+',   short: 'D+', color: '#0E47BA' },
};

const NEKO_CATS = {
  movie:   { id: 'movie',   ko: '영화',   en: 'Movie',   color: '#C4A35A' },  // amber
  series:  { id: 'series',  ko: '시리즈', en: 'Series',  color: '#9B8AE0' },  // violet
  variety: { id: 'variety', ko: '예능',   en: 'Variety', color: '#E08A6C' },  // coral
};

const NEKO_WORKS = [
  // ── 한국 영화 ──────────────────────────────────────
  {
    id: 'decision-to-leave',
    title: '헤어질 결심',
    titleEn: 'Decision to Leave',
    cat: 'movie',
    year: 2022,
    rating: 7.3,
    runtime: 138,
    otts: ['watcha', 'wavve'],
    director: '박찬욱',
    cast: ['탕웨이', '박해일', '이정현', '고경표'],
    genres: ['미스터리', '로맨스', '드라마'],
    overview: '산 정상에서 추락사한 한 남자의 사건을 수사하게 된 형사 해준은 사망자의 아내 서래를 만난다. 그녀의 미스터리한 분위기에 끌리며 의심과 매혹 사이를 오간다.',
    reason: '안개 같은 시선과 여백, 천천히 곱씹기 좋아요',
    isNew: false, savedDaysAgo: 3, watched: false,
  },
  {
    id: 'parasite',
    title: '기생충',
    titleEn: 'Parasite',
    cat: 'movie',
    year: 2019,
    rating: 8.5,
    runtime: 132,
    otts: ['netflix', 'watcha'],
    director: '봉준호',
    cast: ['송강호', '이선균', '조여정', '최우식'],
    genres: ['스릴러', '블랙코미디', '드라마'],
    overview: '전원 백수인 기택네 장남 기우가 고액 과외 면접을 위해 박 사장 집에 발을 들이며 시작되는 두 가족의 만남.',
    reason: '계급의 균열, 한 컷 한 컷이 다큐멘터리처럼 살아있어요',
    isNew: false, savedDaysAgo: 14, watched: true,
  },
  {
    id: 'oldboy',
    title: '올드보이',
    titleEn: 'Oldboy',
    cat: 'movie',
    year: 2003,
    rating: 8.2,
    runtime: 120,
    otts: ['netflix', 'tving', 'wavve'],
    director: '박찬욱',
    cast: ['최민식', '유지태', '강혜정', '지대한'],
    genres: ['스릴러', '미스터리', '액션'],
    overview: '15년간 영문도 모른 채 사설 감금방에 갇혀 있던 오대수가 풀려난 뒤, 자신을 가둔 자를 추적하기 시작한다.',
    reason: '장르의 경계를 초월하는 강렬한 스릴러, 인간 본성의 깊은 고찰',
    isNew: false, savedDaysAgo: 30, watched: true,
  },
  {
    id: 'past-lives',
    title: '패스트 라이브즈',
    titleEn: 'Past Lives',
    cat: 'movie',
    year: 2023,
    rating: 7.8,
    runtime: 105,
    otts: ['watcha'],
    director: '셀린 송',
    cast: ['그레타 리', '유태오', '존 마가로'],
    genres: ['로맨스', '드라마'],
    overview: '12살에 헤어진 두 사람이 24년 만에 뉴욕에서 재회하면서, 운명과 인연의 의미를 묻는 이틀.',
    reason: '느릿한 호흡으로 멍하게 보기 좋아요',
    isNew: true, savedDaysAgo: 1, watched: false,
  },

  // ── 한국 시리즈 ────────────────────────────────────
  {
    id: 'squid-game',
    title: '오징어 게임',
    titleEn: 'Squid Game',
    cat: 'series',
    year: 2021,
    rating: 7.9,
    seasons: 2,
    otts: ['netflix'],
    director: '황동혁',
    cast: ['이정재', '박해수', '정호연', '오영수'],
    genres: ['스릴러', '서바이벌', '드라마'],
    overview: '빚에 쫓기는 사람들이 거액의 상금을 걸고 의문의 데스 게임에 참가하며 벌어지는 이야기.',
    reason: '몰아보기 좋은 텐션, 한국 사회의 단면을 게임으로 압축했어요',
    isNew: false, savedDaysAgo: 7, watched: false,
  },
  {
    id: 'mask-girl',
    title: '마스크걸',
    titleEn: 'Mask Girl',
    cat: 'series',
    year: 2023,
    rating: 7.2,
    seasons: 1,
    otts: ['netflix'],
    director: '김용훈',
    cast: ['이한별', '나나', '고현정', '안재홍'],
    genres: ['스릴러', '드라마'],
    overview: '외모 콤플렉스로 가면 뒤에 숨어 살아온 김모미가 한 사건을 계기로 인생이 송두리째 흔들리는 이야기.',
    reason: '3부 구성의 변주, 인물별로 카메라가 갈아탑니다',
    isNew: false, savedDaysAgo: 5, watched: false,
  },
  {
    id: 'the-glory',
    title: '더 글로리',
    titleEn: 'The Glory',
    cat: 'series',
    year: 2022,
    rating: 8.1,
    seasons: 1,
    otts: ['netflix'],
    director: '안길호',
    cast: ['송혜교', '이도현', '임지연', '염혜란'],
    genres: ['복수극', '드라마'],
    overview: '학창 시절 끔찍한 폭력의 피해자였던 문동은이 가해자들에게 치밀하게 복수하는 이야기.',
    reason: '느린 칼날, 한 회 한 회가 무겁게 떨어져요',
    isNew: false, savedDaysAgo: 21, watched: true,
  },

  // ── 한국 예능 ──────────────────────────────────────
  {
    id: 'transit-love',
    title: '환승연애',
    titleEn: 'EXchange',
    cat: 'variety',
    year: 2021,
    rating: 8.4,
    seasons: 3,
    otts: ['tving'],
    director: '이진주',
    cast: ['김이나', '유라', '데프콘', '정유미'],
    genres: ['리얼리티', '연애'],
    overview: '헤어진 연인들이 한 집에서 함께 지내며 다시 사랑을 마주하는 리얼리티.',
    reason: '관계의 결을 천천히 들여다보는 시간',
    isNew: true, savedDaysAgo: 2, watched: false,
  },
  {
    id: 'you-quiz',
    title: '유 퀴즈 온 더 블럭',
    titleEn: 'You Quiz on the Block',
    cat: 'variety',
    year: 2018,
    rating: 8.7,
    seasons: 4,
    otts: ['tving', 'wavve'],
    director: '김민석',
    cast: ['유재석', '조세호'],
    genres: ['토크쇼', '리얼리티'],
    overview: '거리에서 만나는 사람들과 나누는 이야기, 그리고 작은 퀴즈.',
    reason: '잔잔한 사람의 결, 한 회만 봐도 따뜻해져요',
    isNew: false, savedDaysAgo: 9, watched: true,
  },

  // ── 글로벌 ─────────────────────────────────────────
  {
    id: 'ozark',
    title: '오자크',
    titleEn: 'Ozark',
    cat: 'series',
    year: 2017,
    rating: 8.2,
    seasons: 4,
    otts: ['netflix'],
    director: '빌 듀빅',
    cast: ['제이슨 베이트먼', '로라 리니', '줄리아 가너'],
    genres: ['범죄', '스릴러', '드라마'],
    overview: '시카고의 재무 설계사 마티 버드가 멕시코 카르텔의 돈세탁에 휘말리며 가족과 함께 미주리 오자크 호수로 옮겨가게 된다.',
    reason: '톤다운된 색채, 차가운 텐션이 좋아요',
    isNew: false, savedDaysAgo: 11, watched: false,
  },
  {
    id: 'interstellar',
    title: '인터스텔라',
    titleEn: 'Interstellar',
    cat: 'movie',
    year: 2014,
    rating: 8.4,
    runtime: 169,
    otts: ['wavve', 'watcha'],
    director: '크리스토퍼 놀란',
    cast: ['매튜 매커너히', '앤 해서웨이', '제시카 차스테인', '마이클 케인'],
    genres: ['SF', '드라마', '모험'],
    overview: '황폐해진 지구를 떠나 새로운 행성을 찾아 나선 우주인들의 여정. 시간과 사랑에 대한 서사적 SF.',
    reason: '큰 스케일의 슬픔, 한 번 더 보고 싶어지는 영화',
    isNew: false, savedDaysAgo: 18, watched: true,
  },
  {
    id: 'dune-2',
    title: '듄: 파트2',
    titleEn: 'Dune: Part Two',
    cat: 'movie',
    year: 2024,
    rating: 8.2,
    runtime: 166,
    otts: ['disney'],
    director: '드니 빌뇌브',
    cast: ['티모시 샬라메', '젠데이아', '레베카 퍼거슨', '오스틴 버틀러'],
    genres: ['SF', '모험', '액션'],
    overview: '폴 아트레이데스가 프레멘과 함께 사막 행성 아라키스에서 가문의 복수를 시작한다.',
    reason: '사막의 숨소리, 사운드 디자인이 압도적이에요',
    isNew: true, savedDaysAgo: 0, watched: false,
  },
];

window.NekoData = { OTTS: NEKO_OTTS, CATS: NEKO_CATS, WORKS: NEKO_WORKS };

// ── Compute poster + backdrop placeholders at load time ─────────
NEKO_WORKS.forEach(w => {
  w.poster   = window.NekoMakePoster   ? window.NekoMakePoster(w)   : '';
  w.backdrop = window.NekoMakeBackdrop ? window.NekoMakeBackdrop(w) : '';
});

