import type { Recommendation } from './types';

export const mockRecommendations: Recommendation[] = [
  {
    title: '기생충',
    titleEn: 'Parasite',
    type: 'movie',
    reason: '계급 풍자와 스릴러를 한 그릇에 담은 봉준호의 대표작',
    tmdbId: 496243,
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    rating: 8.5,
    date: '2019-05-30',
    overview: '반지하 가족이 부잣집에 하나씩 침투하며 벌어지는 이야기.',
    providers: [{ name: 'Netflix', logoUrl: null }],
    watchLink: null,
  },
  {
    title: '오징어 게임',
    titleEn: 'Squid Game',
    type: 'series',
    reason: '456명의 참가자, 456억의 상금. 생존 데스게임 열풍을 일으킨 작품',
    tmdbId: 93405,
    posterUrl: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    rating: 7.8,
    date: '2021-09-17',
    overview: '거액의 상금을 걸고 목숨을 건 서바이벌 게임에 참가한 사람들의 이야기.',
    providers: [{ name: 'Netflix', logoUrl: null }],
    watchLink: null,
  },
  {
    title: '버닝',
    titleEn: 'Burning',
    type: 'movie',
    reason: '무라카미 하루키 원작, 이창동 감독의 미스터리 심리 드라마',
    tmdbId: 491584,
    posterUrl: 'https://image.tmdb.org/t/p/w500/7aCD8SYCYARdcUhWzbN9K5uipfA.jpg',
    rating: 7.5,
    date: '2018-05-17',
    overview: '우연히 재회한 옛 친구와 수수께끼의 남자 사이에서 벌어지는 이야기.',
    providers: [{ name: 'Netflix', logoUrl: null }],
    watchLink: null,
  },
];
